{% set name = "mdonatello" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdonatello-{{ version }}.tar.gz
  sha256: 719784cb4fc8a64a4df1aef484eac7e6220a142ea2b39db90e87056459b097d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  
requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.2
    - versioningit
  run:
    - python >={{ python_min }}
    - mdanalysis >=2.0.0
    - notebook
    - ipywidgets
    - rdkit

test:
  imports:
    - mdonatello
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/talagayev/MDonatello
  summary: '2D small molecule visualization for MDAnalysis'
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://mdonatello.readthedocs.io/

extra:
  recipe-maintainers:
    - talagayev
